site_name: 'new'
site_description: 'Main documentation for the new'
repo_url: https://github.com/suneendralsr/new
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'